import React,{useMemo,useState,useEffect}from"react";import{workbookData}from"./data";import"./styles.css";
const K="altas-tiendas-clean-v8";
const YESNO=["Alta cuenta bancaria","Alta Establecimiento","Alta alta de shop","Carga de catalogo","Alta Producteca","Alta OCA","Alta Módulo Logístico","Alta flete propio","Alta ID Site Payway","Alta MODO","Compra de prueba","Compra de Prueba","Devolución","Carta acuerdo","Carga de campañas","Confirmación CAT","Establecimiento Rebranding","Es seller MOTO","ID Site","Enviamos formulario - Shop","Confirmación Catalogo","Adenda prestamo"];
const ACT=["ID Site","Accesos","Carga de matriz","Carga de catálogo","Always ON","Compra de Prueba","Confirmación CAT","Config. Plan","Prestamos","Prueba realizada","Alta Finalizada","Apagado"];
const OPS=Object.fromEntries([...YESNO.map(f=>[f,["","Si","No"]]),["Activación",["",...ACT]]]);
const V=v=>v===true?"Si":v===false?"No":v??"",empty=v=>v==null||String(v).trim()==="",dropCol=h=>String(h).trim().toLowerCase()==="columna 20";
const yn=v=>{if(v===true)return"Si";if(v===false)return"No";let x=String(v??"").trim(),l=x.toLowerCase();if(["sí","si","true","1","ok","x","yes"].includes(l))return"Si";if(["no","false","0"].includes(l))return"No";return x};
const N=r=>r?.Seller||r?.SELLER||r?.Sellers||r?.["Sellers "]||r?.["Nombre de fantasía"]||r?.["Razón social"]||r?.["Razon social"]||r?.["Razon Social"]||r?.CUIT||"Sin nombre";
const C=r=>r?.CUIT||r?.Cuit||r?.cuit||"",E=r=>r?.["Activación"]||r?.ESTADO||r?.Estado||r?.Status||r?.Satus||r?.Activación||r?.Activacion||r?.["Alta shop"]||"";
const sellerSheet=s=>s&&Array.isArray(s.rows)&&Array.isArray(s.headers)&&s.rows.length&&s.headers.some(h=>/seller|raz[oó]n|cuit|fantas/i.test(String(h)));
function normalize(raw){const w=raw&&Array.isArray(raw.sheets)?raw:workbookData;return{...w,source:"Altas Tiendas",sheets:(w.sheets||[]).map(s=>{let headers=(s.headers||[]).filter(h=>!dropCol(h)&&h!=="Activasión");YESNO.forEach(f=>{if(!headers.includes(f))headers.push(f)});if(!headers.includes("Activación"))headers.push("Activación");let rows=(s.rows||[]).map(r=>{let o={};Object.entries(r||{}).forEach(([k,v])=>{if(!dropCol(k)&&k!=="Activasión")o[k]=v;if(k==="Activasión"&&!o["Activación"])o["Activación"]=v});YESNO.forEach(f=>o[f]=yn(o[f]));o["Activación"]=o["Activación"]||"";return o});return{...s,headers,rows}})}}
function load(){try{let c=localStorage.getItem(K);if(c)return normalize(JSON.parse(c))}catch(e){localStorage.removeItem(K)}return normalize(workbookData)}
function group(headers,row){const main=["Seller","SELLER","Sellers","Sellers ","Nombre de fantasía","Razón social","Razon social","Razon Social","CUIT","Cuit","cuit","Activación","ESTADO","Estado","Status","Satus"],status=YESNO.concat(["Activación"]);let a=[],b=[],c=[];(headers||[]).forEach(h=>{if(OPS[h]||status.includes(h))b.push(h);else if(main.includes(h))a.push(h);else if(!empty(row?.[h]))c.push(h)});return[["Datos principales",a],["Estado y altas",b],["Información adicional",c]]}
export default function App(){const[data,setData]=useState(load),sheets=useMemo(()=>Array.isArray(data?.sheets)?data.sheets.filter(sellerSheet):[],[data]),[tab,setTab]=useState(""),[q,setQ]=useState(""),[idx,setIdx]=useState(0);
useEffect(()=>{if(!tab&&sheets[0]?.name)setTab(sheets[0].name);if(tab&&!sheets.some(s=>s.name===tab)&&sheets[0]?.name)setTab(sheets[0].name)},[sheets,tab]);
useEffect(()=>{try{localStorage.setItem(K,JSON.stringify(data))}catch(e){}},[data]);
const active=useMemo(()=>sheets.find(s=>s.name===tab)||sheets[0]||null,[sheets,tab]);
useEffect(()=>setIdx(0),[active?.name]);
const filtered=useMemo(()=>{let rows=active?.rows||[],t=q.toLowerCase(),a=rows.map((r,i)=>[r,i]);return t?a.filter(([r])=>JSON.stringify(r||{}).toLowerCase().includes(t)):a},[active,q]);
const safeIdx=active?.rows?.[idx]?idx:(filtered[0]?.[1]??0),row=active?.rows?.[safeIdx]||filtered[0]?.[0]||{};
function upd(k,v){if(!active)return;setData(d=>({...d,sheets:(d.sheets||[]).map(s=>s.name!==active.name?s:{...s,rows:(s.rows||[]).map((r,i)=>i===safeIdx?{...r,[k]:v}:r)})}))}
function add(){if(!active)return;let o={};(active.headers||[]).forEach(h=>o[h]="");setData(d=>({...d,sheets:(d.sheets||[]).map(s=>s.name!==active.name?s:{...s,rows:[o,...(s.rows||[])]})}));setIdx(0)}
function field(h){let v=V(row?.[h]);if(OPS[h])return <label className="field compact" key={h}><span>{h}</span><select value={v} onChange={e=>upd(h,e.target.value)}>{OPS[h].includes(v)?null:<option>{v}</option>}{OPS[h].map(o=><option key={o} value={o}>{o||"Sin definir"}</option>)}</select></label>;if(empty(v))return null;return <label className="field" key={h}><span>{h}</span><textarea value={v} onChange={e=>upd(h,e.target.value)}/></label>}
if(!active)return <main><header><h1>Altas Tiendas</h1></header><section className="card"><p>No hay solapas disponibles para mostrar.</p></section></main>;
let headers=active.headers||Object.keys(row||{});
return <main><header><div><h1>Altas Tiendas</h1></div></header><nav>{sheets.map(s=><button className={s.name===active.name?"on":""}onClick={()=>{setTab(s.name);setIdx(0)}} key={s.name}>{s.name}</button>)}</nav><section className="grid"><aside className="card sidebar"><div className="side-title"><h2>Sellers</h2><button onClick={add}>+ Nuevo</button></div><input placeholder="Buscar seller, CUIT o estado..." value={q} onChange={e=>setQ(e.target.value)}/><div className="list">{filtered.slice(0,500).map(([r,i])=><button className={i===safeIdx?"sel":""}key={i}onClick={()=>setIdx(i)}><b>{N(r)}</b><small>{C(r)} {E(r)?`· ${E(r)}`:""}</small></button>)}</div></aside><section className="card detail"><div className="detail-head"><div><h2>{N(row)}</h2><p>{active.name} · fila {safeIdx+1}</p></div>{C(row)&&<span className="pill">{C(row)}</span>}</div>{group(headers,row).map(([title,hs])=>hs.length?<section className="block" key={title}><h3>{title}</h3><div className="fields">{hs.map(field)}</div></section>:null)}</section></section></main>}
